### PR TITLE
Update stac_dist/Local_research_outcomes/Local_research_outcomes.json

### PR DESCRIPTION
**Pull request by baloola**
{"filename": "Local_research_outcomes/Local_research_outcomes.json", "item_type": "stac_dist", "change_type": "Update", "user": "fairicube", "data_owner": true}

### CODE REVIEW

**Comment by misev** [comment]
@vittekm please provide details on how to download the data.

**Comment by robknapen** [comment]
This request looks incomplete and perhaps is intended as a placeholder to be filled-in later. Can you check please @vittekm?

**Comment by vittekm** [comment]
This request is no more need to be kept as active. Either we will not need dataset at all, only need sub-selection or Name/ID has to be adapted to describe more accurately content. Therefore new request has to be submitted.

**Comment by misev** [comment]
@baloola please delete this data request

**Pull request closed without merging**
