### PR TITLE
Update stac_dist/corine_land_cover/corine_land_cover.json-2

### PR DESCRIPTION
**Pull request by baloola**

### CODE REVIEW

**Comment by misev** [comment]
I have the same issue with updating the catalog entry for corine_land_cover as before with LGN: clicking Submit doesn't do anything.

**Comment by baloola** [comment]
I couldn't reproduce the issue, probably an issue caused by a value in the submitted form, our monitoring system needs a little bit of work, once I get the logs from the backend I'll get more insights about the error.

**Comment by misev** [comment]
I saved my input in case you want to try with replicating it: [catalog-editor.eoxhub.fairicube.eu.zip](https://github.com/user-attachments/files/16165542/catalog-editor.eoxhub.fairicube.eu.zip)

**Comment by baloola** [comment]
Thanks @misev, could you try again ?

**Comment by misev** [comment]
@KathiSchleidt please check this metadata merge PR.

In addition I think the following people should check as well:

-    "use_case_S4E": 1, @mari-s4e @MarvinMosel  ?
-    "use_case_NHM": 1, @Susannaioni or @sonjastndl ?
-    "use_case_WER": 2, @robknapen ?

**Comment by misev** [comment]
@KathiSchleidt The data request table in D5.1 looks a bit different from the priorities indicated in the catalog data request, I'm not sure which one is authoritative for requesting UC partner reviews?

Screenshot_20240711_120121

**Comment by Susannaioni** [comment]
> In addition I think the following people should check as well: 
> * "use_case_S4E": 1, @mari-s4e @MarvinMosel  ?
> * "use_case_NHM": 1, @Susannaioni or @sonjastndl ?
> * "use_case_WER": 2, @robknapen ?

@misev yes, UC5 had priority 1 under Corine land cover

**Comment by KathiSchleidt** [comment]
@misev yes, there's a bit of confusion around the UC as NHM ended up doing 2 use cases, both UC3 & UC5 are NHM, whereby UC5 emerged late. In addition, a LOT went wrong with the Inventory Sheet over the last 2 years, UC4 (NILU) is the one UC I'm sure will NOT use CLC!

On `use_case_NHM`, to my memory both NHM UC will probably use CLC
use_case_NHM: @sonjastndl 
use_case_NHM_2: @Susannaioni 

I've added the known suspects as reviewers.

In addition, I noticed a discrepancy between the temporal information in the CLC Coverage vs. the metadata (once more thanks for digging into the available metadata on this, identifying the correct temporal intervals!), in the md record, we still have:

```
"time": {
"extent": [],
"type": "temporal",
"values": [
  "1990-01-01T00:00Z",
  "2000-01-01T00:00Z",
  "2006-01-01T00:00Z",
  "2012-01-01T00:00Z",
  "2018-01-01T00:00Z"
], ...
```

Please align!

**Comment by misev** [comment]
>  In addition, I noticed a discrepancy between the temporal information in the CLC Coverage vs. the metadata

The catalog editor allows to only enter single time points for irregular axis. Not sure how should I indicate the intervals for each slice?

Screenshot_20240715_132746

**Review by robknapen — APPROVED** [review]
Looks ok to me. I still think the interpretation of the temporal dimension is a bit artificial, especially compared to the spatial dimensions. But probably the best possible solution at the moment.

**Comment by misev** [comment]
I realized it may not be obvious how to review the data request @Susannaioni : go to the "Files changed" tab, check the XML (alternatively click Edit on corine_land_cover in the [catalog editor](https://catalog-editor.eoxhub.fairicube.eu/)), then finally click on the green "Review changes" button to approve or something else.

**Review by misev — APPROVED** [review]

**Review by Susannaioni — APPROVED** [review]

**Pull request merged**
