### PR TITLE
ChangeType.update stac_dist/city_features_collection/city_features_collection.json

### PR DESCRIPTION
**Pull request by fairicube-data**
{"filename": "city_features_collection/city_features_collection.json", "item_type": "stac_dist", "change_type": "Update", "user": "FAiRICUBE", "data_owner": true}

### CODE REVIEW

**Comment by KathiSchleidt** [comment]
Just scanned this PR out of curiosity, worried in 2 aspects:
- envelope/bbox seems way larger than the data, just covers EU, but specifies
  - "x" "extent": [-61.119105,55.5130685]
  - "y" "extent": [-21.3035115,65.564344]
- This is a vector dataset (GeoJSON), but we have bands described. Is the plan to try and describe vector datasets using grid concepts?

**Comment by mari-s4e** [comment]
Hi Kathi, thank you for looking into this!

> envelope/bbox seems way larger than the data, just covers EU, but specifies..

double checked the extent, it is correct. Post colonialism has far reaching consequences ;) 

> This is a vector dataset (GeoJSON), but we have bands described. Is the plan to try and describe vector datasets using grid concepts?

I would rather not, but right now the band field in the catalog editor is mandatory, so I added I couple of bands to get past the validation test

**Review by mari-s4e — APPROVED** [review]

**Comment by mari-s4e** [comment]
@eox-cs1 , @baloola this data-request is merged, but it does not show up in the data-access catalog. Why?

**Comment by baloola** [comment]
Thanks @mari-s4e I'll give it a look

**Comment by baloola** [comment]
@mari-s4e  I see that the start date is not before end date. 
```json
"start_datetime": "2024-04-18T00:00Z",
"end_datetime": "2018-12-31T00:00Z",
```
If this is the case I can manually change that ( if you confirm I will do it )

(plus I'll edit the validation script to check that)

**Comment by baloola** [comment]
Yes, I'm working on adding some validation message ( for values that will fail the test but can be submitted ), sorry for the delay

**Comment by baloola** [comment]
done
https://catalog.eoxhub.fairicube.eu/collections/index/items/city_features_collection

**Comment by mari-s4e** [comment]
Thank you Mussab! How does it work now if I need to edit the metadata? Can I do it through the editor?

**Comment by baloola** [comment]
Once you merge the PR, it is no longer possible to edit items via the editor, that is why we ask not to merge PRs except when all the parties involved agree (Data provider, Project lead, CU).
That's been said, I can manually re-create(not revert) the PR again if you want to (but it will not be appearing on the catalog)

**Pull request merged**
